name: Build and Deploy
on:
  push:
    branches: prod
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GIT_CONFIG_NAME: Patrik Dvořáček
          GIT_CONFIG_EMAIL: dvoracek.patrik@gmail.com
          BRANCH: gh-pages
          FOLDER: dist
